codecov:
  notify:
    require_ci_to_pass: no
  # dev should be the baseline for reporting
  branch: Dev

comment:
  layout: "reach, diff"
  behavior: default

coverage:
  range: 70..90
  round: down
  precision: 0

  status:
    project:
      default:
        # Set the overall project code coverage requirement to 90%
        target: 90
    patch:
      default:
        # Set the pull request requirement to not regress overall coverage by more than 5%
        # and let codecov.io set the goal for the code changed in the patch.
        target: auto
        threshold: 5
