name: Code Coverage
on: [push]

jobs:
  CodeCoverage:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
          shell : powershell
          run: |
          $VerbosePreference = 'Continue'
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          $manifest = Import-PowerShellDataFile "./AzDnsAsCode/AzDnsAsCode.psd1"
          $dependencies = $manifest.RequiredModules
          foreach ($dependency in $dependencies)
          {
              Write-Verbose -Message "Installing Module {$($dependency.ModuleName)} Version {$($dependency.RequiredVersion)}"
              Install-Module $dependency.ModuleName -RequiredVersion $dependency.RequiredVersion -Force -SkipPublisherCheck -AllowClobber -Scope AllUsers -Verbose
              try
              {
                  Import-Module $dependency.ModuleName -Force -Verbose
              }
              catch
              {
                  Write-Verbose -Message $_
              }
          }

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}